name: rosaire
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.15.1 <3.5.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.1.1
  intl: ^0.17.0
  google_fonts: ^2.3.1
  just_audio: ^0.9.27
  webview_flutter: ^3.0.4
  flutter_local_notifications: ^9.6.1
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets :
    - assets/EdR_icon.png
    - assets/EdR_splash.png
    - assets/ico1.png
    - assets/ico2.png
    - assets/ico3.png
    - assets/ico4.png

flutter_icons:
  image_path: "assets/EdR_icon.png"
  android: true
  ios: true


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/EdR_splash.png
